name: DB Programming Assignment CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nodejs environment
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"


      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build 
        run: npm run build
        env:
          CI: true